template = "a scene of "
templates = [
    "a photo of a ",
    "a scene of a ",
    "a place of a "
]

scenes = [
    "abbey",
    "airfield",
    "airplane cabin",
    "airport terminal",
    "alcove",
    "alley",
    "amphitheater",
    "amusement arcade",
    "amusement park",
    "apartment building - outdoor",
    "aquarium",
    "aqueduct",
    "arcade",
    "arch",
    "archaelogical excavation",
    "archive",
    "arena - hockey",
    "arena - performance",
    "arena - rodeo",
    "army base",
    "art gallery",
    "art school",
    "art studio",
    "artists loft",
    "assembly line",
    "athletic field - outdoor",
    "atrium - public",
    "attic",
    "auditorium",
    "auto factory",
    "auto showroom",
    "badlands",
    "bakery - shop",
    "balcony - exterior",
    "balcony - interior",
    "ball pit",
    "ballroom",
    "bamboo forest",
    "banquet hall",
    "bar",
    "barn",
    "barndoor",
    "baseball field",
    "basement",
    "basilica",
    "basketball court - indoor",
    "bathroom",
    "bayou",
    "bazaar - indoor",
    "bazaar - outdoor",
    "beach",
    "beach house",
    "beauty salon",
    "bedchamber",
    "bedroom",
    "beer garden",
    "beer hall",
    "berth",
    "bistro - indoor",
    "bistro - outdoor",
    "boardwalk",
    "boat deck",
    "boathouse",
    "bookstore",
    "booth - indoor",
    "botanical garden",
    "bow window - indoor",
    "bowling alley",
    "boxing ring",
    "bridge",
    "building facade",
    "bullring",
    "burial chamber",
    "bus interior",
    "bus station - indoor",
    "butchers shop",
    "butte",
    "cabin - outdoor",
    "cafeteria",
    "campsite",
    "campus",
    "canal - natural",
    "canal - urban",
    "candy store",
    "canyon",
    "car interior - backseat",
    "car interior - frontseat",
    "carrousel",
    "castle",
    "catacomb",
    "cathedral - indoor",
    "cathedral - outdoor",
    "cemetery",
    "chalet",
    "chapel",
    "childs room",
    "church - indoor",
    "church - outdoor",
    "classroom",
    "cliff",
    "closet",
    "clothing store",
    "coast",
    "cockpit",
    "coffee shop",
    "conference center",
    "conference room",
    "construction site",
    "corn field",
    "corral",
    "corridor",
    "cottage",
    "cottage garden",
    "courthouse",
    "courtyard",
    "creek",
    "crevasse",
    "crosswalk",
    "cubicle - office",
    "dam",
    "delicatessen",
    "department store",
    "desert - sand",
    "desert - vegetation",
    "desert road",
    "diner - outdoor",
    "dinette - home",
    "dining hall",
    "dining room",
    "discotheque",
    "dock",
    "doorway - outdoor",
    "dorm room",
    "downtown",
    "driveway",
    "elevator - door",
    "elevator - interior",
    "elevator lobby",
    "elevator shaft",
    "embassy",
    "engine room",
    "entrance hall",
    "escalator - indoor",
    "excavation",
    "fairway",
    "farm",
    "fastfood restaurant",
    "field - cultivated",
    "field - wild",
    "field road",
    "fire escape",
    "fire station",
    "fishpond",
    "flea market - indoor",
    "florist shop - indoor",
    "food court",
    "football field",
    "forest - broadleaf",
    "forest path",
    "forest road",
    "formal garden",
    "fountain",
    "freeway",
    "galley",
    "game room",
    "garage - indoor",
    "garage - outdoor",
    "garbage dump",
    "gas station",
    "gazebo - exterior",
    "general store - indoor",
    "general store - outdoor",
    "gift shop",
    "glacier",
    "golf course",
    "gorge",
    "greenhouse - indoor",
    "greenhouse - outdoor",
    "grotto",
    "gymnasium - indoor",
    "hallway",
    "hangar - indoor",
    "hangar - outdoor",
    "harbor",
    "hardware store",
    "hayfield",
    "heliport",
    "herb garden",
    "highway",
    "home office",
    "home theater",
    "hospital",
    "hospital room",
    "hot spring",
    "hotel - outdoor",
    "hotel room",
    "house",
    "hunting lodge - outdoor",
    "ice cream parlor",
    "ice floe",
    "ice shelf",
    "ice skating rink - indoor",
    "ice skating rink - outdoor",
    "iceberg",
    "igloo",
    "industrial area",
    "industrial park",
    "inn - outdoor",
    "islet",
    "jacuzzi - indoor",
    "jail cell",
    "japanese garden",
    "jewelry shop",
    "junkyard",
    "kasbah",
    "kennel - outdoor",
    "kindergarden classroom",
    "kitchen",
    "kitchenette",
    "lagoon",
    "lake - natural",
    "landfill",
    "landing deck",
    "laundromat",
    "lavatory",
    "lawn",
    "lecture room",
    "legislative chamber",
    "library - indoor",
    "library - outdoor",
    "lift bridge",
    "lighthouse",
    "limousine interior",
    "living room",
    "loading dock",
    "lobby",
    "lock chamber",
    "locker room",
    "mansion",
    "manufactured home",
    "market - indoor",
    "market - outdoor",
    "marsh",
    "martial arts gym",
    "mausoleum",
    "medina",
    "mezzanine",
    "moat - water",
    "monastery - outdoor",
    "mosque - outdoor",
    "motel",
    "mountain",
    "mountain path",
    "mountain snowy",
    "movie theater - indoor",
    "museum - indoor",
    "museum - outdoor",
    "music studio",
    "natural history museum",
    "nursery",
    "nursing home",
    "oast house",
    "ocean",
    "office",
    "office building",
    "office cubicles",
    "oilrig",
    "operating room",
    "orchard",
    "orchestra pit",
    "pagoda",
    "palace",
    "pantry",
    "park",
    "parking garage - indoor",
    "parking garage - outdoor",
    "parking lot",
    "parlor",
    "pasture",
    "patio",
    "pavilion",
    "pet shop",
    "pharmacy",
    "phone booth",
    "physics laboratory",
    "picnic area",
    "pier",
    "pizzeria",
    "playground",
    "playroom",
    "plaza",
    "pond",
    "porch",
    "promenade",
    "pub - indoor",
    "pulpit",
    "putting green",
    "racecourse",
    "raceway",
    "raft",
    "railroad track",
    "rainforest",
    "reading room",
    "reception",
    "recreation room",
    "repair shop",
    "residential neighborhood",
    "restaurant",
    "restaurant kitchen",
    "restaurant patio",
    "rice paddy",
    "riding arena",
    "river",
    "rock arch",
    "roof garden",
    "rope bridge",
    "ruin",
    "runway",
    "sandbar",
    "sandbox",
    "sauna",
    "schoolhouse",
    "science museum",
    "sea cliff",
    "server room",
    "shed",
    "shoe shop",
    "shopfront",
    "shopping mall - indoor",
    "shower",
    "ski lodge",
    "ski resort",
    "ski slope",
    "sky",
    "skyscraper",
    "slum",
    "snowfield",
    "soccer field",
    "stable",
    "stadium - baseball",
    "stadium - football",
    "stadium - soccer",
    "stage - indoor",
    "stage - outdoor",
    "staircase",
    "storage room",
    "street",
    "subway station - platform",
    "supermarket",
    "sushi bar",
    "swamp",
    "swimming hole",
    "swimming pool - indoor",
    "swimming pool - outdoor",
    "synagogue - outdoor",
    "television room",
    "television studio",
    "temple - east asia",
    "temple - south asia",
    "tent - outdoor",
    "throne room",
    "ticket booth",
    "topiary garden",
    "tower",
    "toyshop",
    "track - outdoor",
    "train interior",
    "train railway",
    "train station - platform",
    "tree farm",
    "tree house",
    "trench",
    "tundra",
    "underwater - coral reef",
    "underwater - ocean deep",
    "utility room",
    "valley",
    "vegetable garden",
    "veranda",
    "veterinarians office",
    "viaduct",
    "village",
    "vineyard",
    "volcano",
    "volleyball court - outdoor",
    "waiting room",
    "water park",
    "water tower",
    "waterfall - block",
    "waterfall - fan",
    "waterfall - plunge",
    "watering hole",
    "wave",
    "wet bar",
    "wheat field",
    "wind farm",
    "windmill",
    "woodland",
    "yard",
    "youth hostel",
    "zen garden"
]