# base config
DESCRIPTION: Hematoma segmentation

SEED: 42

# Model
MODEL:
  NAME: vit_giant_lora
  # We init from a pretrained model on LaMem fold 1
  INIT_WEIGHTS: /data/dingsd/projects/img2emo_anyproject/output/clip_trivialaug_lamem/MemCLIPVitLora/clip_lamem_vit_lora_mse_srcc_ccc_ep20/LaMem/seed1_fold1/model/model-best.pth.tar

# Optim
OPTIM:
  NAME: "sgd"
  LR: 1e-3
  WEIGHT_DECAY: 0.   # default is 5e-4
  ADAM_EPS: 1e-8       # fp32/amp 1e-7, fp16 1e-3
  MAX_EPOCH: 40
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5


TRAIN:
  PRINT_FREQ: 50
  GRADIENT_ACCUMULATION_STEPS: 8

TEST:
  EVALUATOR: "Regression"
  OTHER_METRICS: false
  SPLIT: "val"
  FINAL_MODEL: "best_val"   # last_step best_val
  PER_CLASS_RESULT: true
  AVG_ON_DOMAIN: false

# Trainer
TRAINER:
  ENSEMBLEMEMCLIPVITLORA:
    PREC: "amp"
    METHOD: 3   # 1 for mse loss, 2 for mse + srcc loss, 3 for mse + srcc + ccc loss

    LORA_REDUCTION: 8
    HEAD_DROPRATE: 0.

    SRCC_TEMP: 0.1

    INIT_WEIGHTS: [
      '/data/dingsd/projects/img2emo_anyproject/output/clip_trivialaug_lamem/MemCLIPVitLora/clip_lamem_vit_lora_mse_srcc_ccc_ep20/LaMem/seed1_fold1/model/model-best.pth.tar',
      '/data/dingsd/projects/img2emo_anyproject/output/clip_trivialaug_memcat/MemCLIPVitLora/clip_memcat_vit_lora_mse_srcc_ccc_ep20/MemCat/seed1/model/model-best.pth.tar'
    ]