# Dataset
DATASET:
  NAME: GAPED
  ROOT: /opt/dingsd/img2emo/data
  SOURCE_DOMAINS: ['GAPED']
  TARGET_DOMAINS: ['']
  FOLD: 0


DATASET_WRAPPER:
  NAME: DatasetWrapper

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
    SAMPLER: RandomSampler
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 16
  

INPUT:
  SIZE: (224, 224)   # (w, h)
  INTERPOLATION: "bicubic"
  TRANSFORMS: emotic_transform  # a function, emotic_transform

